import './global.css';

export const metadata = {
  title: 'Molly',
  description: 'Generated by Next.js',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className="bg-white">{children}</body>
    </html>
  );
}
